#     # ######
##   ## #     #
# # # # #     #
#  #  # ######
#     # #   #
#     # #    #
#     # #     # Melhem Rizk

format = """
[](#d35400)\
$username\
$os\
[](fg:#ff5500 bg:#1e8449)\
$hostname\
[](fg:#1e8449 bg:#9b59b6)\
$directory\
[](fg:#9b59b6 bg:#21618c)\
$git_branch\
$git_status\
[](fg:#21618c bg:#7d3c98)\
$python\
$conda\
[](fg:#7d3c98 bg:#00aaff)\
$time\
[ ](fg:#00aaff)\
$cmd_duration
➜ (fg:#ffffff)
"""

# Enable the blank line at the start of the prompt
add_newline = true

# Displays the user name
[username]
show_always = true
style_user = "bg:#ff5500 fg:#ffffff"
style_root = "bg:#ff0000 fg:#ffffff"
format = '[$user]($style bold)'
disabled = false

# Displays a symbol of your operating system. Choose which symbol to display in the [os.symbols] module
[os]
style = "bg:#ff5500 fg:#145a32"
format = '[$symbol]($style bold)'
disabled = false # Disabled by default

[os.symbols]
openSUSE = "🦎"

# Dispalys the hostname
[hostname]
ssh_only = false
style = "bg:#1e8449 fg:#ffffff"
format = '[$hostname]($style bold)'
disabled = false

# Displays the current working directory
[directory]
read_only = '🔒'
style = "bg:#9b59b6 fg:#ffffff"
read_only_style = "bg:#9b59b6 fg:#ff0000"
format = "[$path]($style bold italic)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"

# Replace some directories with icons, to shorten the path
#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = " "
#"Pictures" = " "

# Displays the time it takes to execute a command
[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "fg:#de3163 bold italic"


[python]
symbol = "🐍 "
pyenv_version_name = true
format = '[via ${symbol}python (${version} )(\($virtualenv\) )]($style bold)'
style = "bg:#7d3c98 fg:#ffffff"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3"]
detect_extensions = ["py"]
version_format = "v${raw}"


[conda]
symbol = " "
style = "fg:#ffffff bg:#7d3c98"
format = '[$symbol$environment]($style bold)'
disabled = false

[git_branch]
symbol = ""
style = "bg:#21618c fg:#ffffff"
format = '[$symbol $branch]($style)'

[git_status]
style = "bg:#21618c fg:#ffffff"
format = '[$all_status$ahead_behind]($style)'

[golang]
symbol = " "
style = "bg:#7d3c98"
format = '[$symbol ($version)]($style)'


[nodejs]
symbol = ""
style = "bg:#7d3c98"
format = '[$symbol ($version)]($style)'

# Displays the time in 24hr format
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#00aaff fg:#ffffff"
format = '[♥ $time]($style bold)'



